### ISSUE TITLE
Unable to view `/new`

### ISSUE THREAD

**Issue by jtslear** [jtslear/rumbl#1]
@drapergeek I'm unable to view the path `/new` for some reason.  

```
[info] GET /users/new
[debug] Processing by Rumbl.UserController.show/2
  Parameters: %{"id" => "new"}
  Pipelines: [:browser]
[info] Sent 400 in 50ms
[debug] ** (Ecto.CastError) deps/ecto/lib/ecto/repo/queryable.ex:188: value `"new"` in `where` cannot be cast to type :id in query:

from u in Rumbl.User,
  where: u.id == ^"new"

Error when casting value to `Rumbl.User.id`
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/repo/queryable.ex:91: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:15: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:44: Ecto.Repo.Queryable.one/4
    (rumbl) web/controllers/user_controller.ex:16: Rumbl.UserController.show/2
    (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.action/2
    (rumbl) web/controllers/user_controller.ex:1: Rumbl.UserController.phoenix_controller_pipeline/2
    (rumbl) lib/phoenix/router.ex:261: Rumbl.Router.dispatch/2
    (rumbl) web/router.ex:1: Rumbl.Router.do_call/2
    (rumbl) lib/rumbl/endpoint.ex:1: Rumbl.Endpoint.phoenix_pipeline/1
```

I'm following chapter 4 here.  Any advice?

**Comment by drapergeek** [comment]
Check your routes file. It is trying to send you to the 'show' action instead of the 'new' action.
