### ISSUE TITLE
Unable to compile missing function?

### ISSUE THREAD

**Issue by jtslear** [jtslear/rumbl#2]
@drapergeek, 

I'm unable to compile due to the below
https://github.com/jtslear/rumbl/blob/master/web/controllers/auth.ex#L26  Using library: https://hexdocs.pm/comeonin/api-reference.html

```
== Compilation error on file web/controllers/auth.ex ==
** (CompileError) web/controllers/auth.ex:26: undefined function checkpw/2
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:116: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by drapergeek** [comment]
@jtslear that fucntion has not been imported or aliased so you can't use just the short version of it.

``` elixir
Comeonin.Bcrypt.check_pw(given_pass, user.password_hash)
```

or 

``` elixir
import ComeonIn.Bcrypt, only: [check_pw: 2]
```

or

``` elixir
alias Comeonin.Bcrypt

Bcrypt.check_pw(given_pass, user.password_hash)
```

should take care of it.

FWIW, I'd probably use the 1st option as it makes it clear what you're using and where it came from since that is the only function from that library you're using in this file and you're only using it once.
